### ISSUE TITLE
panel and games page (priority)

### ISSUE THREAD

**Issue by mehdimz** [ahoseinian/gaming#13]
tu panel ghesmate bazi ha 2ta field gozashti vase gereftane aks ke yekish namayeshesh dar bannere yekish ham aksie ke tu safeye bazi miofte... vaghti aksi ke ruye safeye bazi mikhaim bezarim o upload mikonim tu safeye bazi taghiri ijad nemishe...
size e bannere dakhele safeye bazi (games) hamun 1600*645 e.
age be manam begi in andaze ha az koja taghir mikone kheili khub mishe.

**Comment by ahoseinian** [comment]
kon golabi englisi benevis kelas dare

**Comment by ahoseinian** [comment]
It seems that I've not understood you, because I've just changed the hearthstone game main image, and it is working fine!

please let me know if your problem still exists.
