### ISSUE TITLE
image size increases !!!

### ISSUE THREAD

**Issue by mehdimz** [ahoseinian/gaming#15]
slider image size increases after uploading an image... for instance: 100kb image increases to 400kb after upload
im not sure if its effected on carousel images aswell
Troubleshoot it please  (tonight if possible)

**Comment by ahoseinian** [comment]
It should be fixed now

**Comment by ahoseinian** [comment]
close the issue if it is fixed please

**Comment by mehdimz** [comment]
unfortunately the issue still exists
