### ISSUE TITLE
additional pictures problemS

### ISSUE THREAD

**Issue by mehdimz** [ahoseinian/gaming#21]
1- Image gallery for big images is needed. more info: https://html.nkdev.info/youplay/dark/store-product-1.

2- Images on additional picture (carousel section) must be as the same size as the slider carousel on index page (same width and same height)... this issue happened due to wrong conversion... however, there is no need to be any conversion for big images. just let the image be as its original size.

3- three additional images added on World of Warcraft game which has to be either replaced or deleted. any special way to delete or replace additional images?

**Comment by ahoseinian** [comment]
It is been fixed

**Comment by mehdimz** [comment]
issues number 2 and 3 still exists
![zx](https://cloud.githubusercontent.com/assets/19794688/16151242/84223e70-3461-11e6-9279-9c28c1a54991.jpg)
![zxx](https://cloud.githubusercontent.com/assets/19794688/16151257/97067060-3461-11e6-93a1-e8ec9669ef81.jpg)

no conversion needed on big images (modal)... let the original size be (if possible)... no need to covert it to 1600

**Comment by ahoseinian** [comment]
we have to talk about it on TS later
