### ISSUE TITLE
based on platform page

### ISSUE THREAD

**Issue by mehdimz** [ahoseinian/gaming#70]
based on platform page has no separations... it must be : bazi haye PC , bazi haye ps4, bazi haye xbox and...

**Comment by ahoseinian** [comment]
I don't get what you mean

**Comment by mehdimz** [comment]
yani man vaghti ru menu e bazi ha > bar asase platform > PC   o select mikonam title esh bayad beshe bazi haye PC va faghat bazi hayi ke platformeshun PC hasto namayesh bede... alan vaghti in karo mikonam hameye bazi ha ro namayesh mide
